---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
type: Opaque
data:
  host: cmFiYml0bXEucmFiYml0bXEuc3ZjLmNsdXN0ZXIubG9jYWw=  # Base64 encoded RabbitMQ host
  queueName: dGVzdF9xdWV1ZQ==                          # Base64 encoded queue name
  username: dXNlcg==                                  # Base64 encoded username
  password: cGFzc3dvcmQ=                              # Base64 encoded password
