apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: rabbitmq
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: host
    - parameter: queueName
      name: rabbitmq-secret
      key: queueName
    - parameter: username
      name: rabbitmq-secret
      key: username
    - parameter: password
      name: rabbitmq-secret
      key: password
